### PR TITLE
Change b-form-select to b-dropdown

### LINKED ISSUE #209: Change the cursor to a pointer when hovering over clickable items.
**Describe the bug**
When a user hovers over items that are clickable such as the drop down lists and the list items the cursor should change to a pointer. ( the little hand that points it's finger )

Currently this does not happen on the drop downs or the list items on the left.

**To Reproduce**
1. Hover over the drop down lists
2. It should be showing the pointer, but it currently is not.

3. Select any business type
4. Hover over the list items on the left
5. The pointer should also change, but currently it is not.

### PR DESCRIPTION
**Pull request by aevix**
In the file SearchFilter.vue the b-form-select uses options tag to render the dropdown menu so I tried just changing the css cursor option to pointer but didn't seem to work so I found out that the options tag is rendered using the user OS so that's why on the screen shots of mac and windows dropdown menus looks different.
I did some digging and found out b-dropdown allows me to not only change the cursor to pointer but also makes sure that the dropdown menu is the same on all platforms. I managed to get it to work with all the buttons but there maybe some unforeseen bugs and probably needs adjustment to make it look the way you want it in styling. Fixes #209 
Let me know what you think and if this could be a solution to issue209

### CODE REVIEW

**Comment by readingdancer** [comment]
Hi @aevix - Could you let me know why you have submitted this PR? I.e. what was the reason for the change?

( Thanks for submitting it.. I just wanted to understand the reason for it )

**Comment by aevix** [comment]
@readingdancer I am sorry it wasn't clear what it was for. I submitted this for issue 209 where the mouse cursor doesn't change to pointer when you mouse over the drop down options and it was because the options tag is rendered through the operating system not the client browser so I changed the tag and it was able to change it to a pointer. One problem with this is that it changed the way the dropdown menu is styled so I don't know if you wanted to use it but I figured I would create a PR just so you can see the difference.

**Comment by readingdancer** [comment]
I am trying to bring this project back to live as I rather dropped the ball last summer and no one else seemed to be interested to catch it. I am going to see if I can get the current PR's either merged in or closed so we have a clean slate, hence my updating the PR's now and I will start looking at them tomorrow.

**Comment by readingdancer** [comment]
Thank you again, obviously this project is no longer active so I am closing this PR.

**Pull request closed without merging**
