### PR TITLE
Issue 172

### PR DESCRIPTION
**Pull request by pa2nther**
Added a option for Issue 172 Speciality Food & drink in dropbox. Did not pull any options. Are there any in this category in the database?

### CODE REVIEW

**Comment by KM-Hanson** [comment]
Hi @pa2nther , @readingdancer 

Yes - there are resources tagged as food_bev in the database. I just changed a few more that were initially tagged as restaurants. Feel free to reach out if you are still having issues.

**Comment by readingdancer** [comment]
Hi @pa2nther thank you for submitting the PR, I am right in the middle of a big refactor which I am hoping to complete this evening. I will hopefully get to checking your PR tomorrow morning to give you some feedback / or merge in if everything is good :)

Thank you again for submitting a PR, we really appreciate it 👍

**Comment by readingdancer** [comment]
Just a quick comment, when you select items the top section should be showing the summaries in the same way as the restaurant section, I couldn't see anything in your code that touched that area, so it might be missing, unless it is the default setting!? I can't remember off the top of my head, but perhaps you could check it?

**Comment by readingdancer** [comment]
FYI, I will need to update the other language files before we push this live, hopefully at some point over this weekend.

**Comment by readingdancer** [comment]
This commit closes issue #172

**Pull request merged**
