### PR TITLE
add more whitelist item

### PR DESCRIPTION
**Pull request by aevix**
added more whitelist items to stop purging the language selection dropdown menu

### CODE REVIEW

**Comment by aevix** [comment]
@readingdancer Unit tests is broken on master

**Comment by aevix** [comment]
@readingdancer Hi, I was wondering if this PR fixes the issue of purging let me know if this was what you were looking for regarding issue-246

**Comment by readingdancer** [comment]
Hi, Sorry I have been very busy and not had time to look at your PR yet, I do apologize for not getting back to you sooner, it has been on my radar to do. Have you closed it because you think it's no longer valid?

**Comment by aevix** [comment]
@readingdancer I saw someone already was working on this issue so I wasn't sure if this was solved already or not I am very new github and opensource so I wasn't sure if I was doing it right haha.

**Pull request closed without merging**
