### PR TITLE
Show only three buttons on mobile

### PR DESCRIPTION
**Pull request by jklafka**
Re: issue #259, I worked on the first part of this. On the mobile webpage, only the options to call the location, get directions or go to the website (if available) will show.

### CODE REVIEW

**Comment by readingdancer** [comment]
Hi @jklafka - Thank you for trying to take a look at this, unfortunately this is not quite what we have envisaged. We do want all the details to be viewable when a user pulls the card up from the bottom of the screen, so we don't actually want to hide the items on mobile.

If it's ok, I suggest we close this PR.

If you'd still like to try and help tackle it, perhaps we could have a call next week to discuss it?

**Comment by jklafka** [comment]
Sure, I'd be happy to talk about how to move forward on this next week. Do you have time next weekend to discuss it? And would you still like me to close this pull request?

**Comment by readingdancer** [comment]
Hi @jklafka - Really sorry that this was not followed up back in September of last year, I was a bit overwhelmed with homeschooling two children and life in general that this project got sidelined by me and no one else too over the reigns. I am trying to bring it back to life, so I will try and take a look at your PR this week, however it may well be too conflicting with the other changes to merge in, we will have to see :)

**Comment by jklafka** [comment]
Absolutely, no problem. To be honest, I'm not familiar with Vue.js, so worries if you have to throw the PR out! Hope you can get back into this project soon.

**Comment by readingdancer** [comment]
Thank you again, obviously this project is no longer active so I am closing this PR.

**Pull request closed without merging**
